version: '3.4'

services:
  postgres:
    image: postgres
    container_name: teste_postgres
    environment:
      POSTGRES_PASSWORD: "Postgres2024!"
    ports:
      - "5432:5432"
    volumes:
      - postgres 
    networks:
      - educacoopern
      
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "westefns@outlook.com.br"
      PGADMIN_DEFAULT_PASSWORD: "PgAdmin2024!"
    ports:
      - "16543:80"
    depends_on:
      - postgres
    networks:
      - educacoopern
  
  educacoopern:
    image: ${DOCKER_REGISTRY-}educacoopern
    container_name: educacoopern
    build:
      context: .
      dockerfile: EDUCACOOPERN/Dockerfile
    ports:
      - "8080:8080"
      - "8081:8081"
    depends_on:
      - postgres
    networks:
      - educacoopern
  
networks: 
  educacoopern:
    driver: bridge
