version: '3.4'

services:
  postgres:
    image: postgres
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "Postgres2024!"
      POSTGRES_DB: ecudacoopern
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "westefns@outlook.com.br"
      PGADMIN_DEFAULT_PASSWORD: "PgAdmin2024!"
    ports:
      - "16543:80"
    depends_on:
      - postgres

volumes:
  postgres_data: